#!/bin/bash
# ============================================================================
# Register ONE system: any receptor PDB, optionally with a docked ligand pose.
# This is the only place you name an input file -- nothing downstream is edited.
#
#   ./new_system.sh eg1_m08_X6 \
#        --receptor ../EG1/models/fold_m08_1ks5backbone_1xyninsert_model_0.pdb \
#        --ligand X6 \
#        --pose ../EG1/models/docking/<model>/<model>_X6_ad4_out.pdbqt
#
#   ./new_system.sh eg1_m08_apo \
#        --receptor ../EG1/models/fold_m08_1ks5backbone_1xyninsert_model_0.pdb
#
# Options:
#   --chain A        which chain to keep (default A)
#   --pose-index N   which docked pose (default 1 = best affinity)
#   --force          overwrite a system that already exists
#
# It writes systems/<name>.conf and build/<name>/{protein.pdb,ligand_af3.pdb},
# then stops. Building the system is prep_system.sh's job; this only decides
# WHAT is being built, and records the expectations prep_system.sh checks
# against (residue count, histidines, net charge).
# ============================================================================
set -u
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${SCRIPT_DIR}"
# shellcheck source=/dev/null
[ -r config.sh ] && source config.sh          # so N_REPS below is the real number

NAME=""; RECEPTOR=""; LIGAND=""; POSE=""; CHAIN="A"; POSE_INDEX=1; FORCE=0
while [ $# -gt 0 ]; do
  case "$1" in
    --receptor)   RECEPTOR="$2"; shift 2 ;;
    --ligand)     LIGAND="$2";   shift 2 ;;
    --pose)       POSE="$2";     shift 2 ;;
    --chain)      CHAIN="$2";    shift 2 ;;
    --pose-index) POSE_INDEX="$2"; shift 2 ;;
    --force)      FORCE=1; shift ;;
    -h|--help)    sed -n '2,25p' "$0"; exit 0 ;;
    -*)           echo "unknown option: $1"; exit 1 ;;
    *)            [ -z "${NAME}" ] && NAME="$1" || { echo "unexpected argument: $1"; exit 1; }; shift ;;
  esac
done

[ -n "${NAME}" ]     || { echo "ERROR: no system name given. See ./new_system.sh --help"; exit 1; }
[ -n "${RECEPTOR}" ] || { echo "ERROR: --receptor is required."; exit 1; }
[ -f "${RECEPTOR}" ] || { echo "ERROR: no such receptor file: ${RECEPTOR}"; exit 1; }
case "${NAME}" in *[!A-Za-z0-9_-]*)
  echo "ERROR: '${NAME}' has characters that will break file names. Use [A-Za-z0-9_-]."; exit 1 ;;
esac
if [ -e "systems/${NAME}.conf" ] && [ "${FORCE}" != "1" ]; then
  echo "ERROR: systems/${NAME}.conf already exists. Use --force to replace it."; exit 1
fi

# A ligand needs BOTH a pose and a CHARMM topology. Refusing here is much
# cheaper than a build that dies after pdb2gmx, and much safer than silently
# producing an apo system when a holo one was meant.
HAS_LIGAND=0
if [ -n "${LIGAND}" ] || [ -n "${POSE}" ]; then
  [ -n "${LIGAND}" ] || { echo "ERROR: --pose given without --ligand."; exit 1; }
  [ -n "${POSE}" ]   || { echo "ERROR: --ligand given without --pose."; exit 1; }
  [ -f "${POSE}" ]   || { echo "ERROR: no such pose file: ${POSE}"; exit 1; }
  if [ ! -f "ligands/${LIGAND}_charmm/${LIGAND}.itp" ]; then
    echo "ERROR: no CHARMM topology for '${LIGAND}'."
    echo "       Expected: ligands/${LIGAND}_charmm/${LIGAND}.itp"
    echo "       CHARMM36's GROMACS port has no glycosidic patch, so pdb2gmx cannot"
    echo "       build an oligosaccharide. Generate the topology once in CHARMM-GUI;"
    echo "       see ligands/README.md."
    exit 1
  fi
  HAS_LIGAND=1
fi

mkdir -p "build/${NAME}" systems
echo "=========================================================="
echo "system     : ${NAME}"
echo "=========================================================="
NRES=$(python3 prep_receptor.py "${RECEPTOR}" "build/${NAME}/protein.pdb" --chain "${CHAIN}" \
       | tee /dev/stderr | awk '/residues  :/{print $3}')
[ -n "${NRES}" ] || { echo "ERROR: receptor preparation failed."; exit 1; }

if [ "${HAS_LIGAND}" = "1" ]; then
  echo ""
  python3 pose_from_docking.py "${POSE}" "build/${NAME}/ligand_af3.pdb" --pose "${POSE_INDEX}" \
    || exit 1
fi

# Expectations prep_system.sh will check what pdb2gmx ACTUALLY built against.
# Counted from the cleaned receptor, not guessed: a mismatch later means the
# structure and the intent disagree, which is the failure worth catching.
NHIS=$(awk '$1=="ATOM" && substr($0,13,4)~/ CA / {print substr($0,18,3)}' "build/${NAME}/protein.pdb" | grep -c HIS)
CHG=$(awk '$1=="ATOM" && substr($0,13,4)~/ CA / {print substr($0,18,3)}' "build/${NAME}/protein.pdb" \
      | awk '/ARG|LYS/{p++} /ASP|GLU/{m++} END{print (p+0)-(m+0)}')
# +1 charged N-terminus, -1 charged C-terminus -> they cancel; histidines are
# built neutral by pdb2gmx at pH 7, so they contribute 0.
cat > "systems/${NAME}.conf" <<EOF
# ${NAME} -- generated by new_system.sh on $(date +%Y-%m-%d)
# Sourced by prep_system.sh AFTER config.sh: per-molecule facts only.

RECEPTOR_SRC=${RECEPTOR}
CHAIN=${CHAIN}
N_RESIDUES=${NRES}

# Checked against what pdb2gmx actually builds. If the build disagrees, the
# structure is not what this file says it is -- find out why before continuing.
EXPECT_DISULFIDES=0
EXPECT_HIS=${NHIS}
EXPECT_CHARGE=${CHG}

# 1 = a ligand is merged in from build/${NAME}/glycan.itp (built by
# 02_build_glycan.py from the docked pose). 0 = protein only.
HAS_LIGAND=${HAS_LIGAND}
LIGAND=${LIGAND}
POSE_SRC=${POSE}
POSE_INDEX=${POSE_INDEX}
EOF

echo ""
echo "  histidines : ${NHIS}      (pdb2gmx builds these neutral at pH 7)"
echo "  net charge : ${CHG}       (Arg+Lys - Asp+Glu; termini cancel)"
echo "  wrote      : systems/${NAME}.conf"
echo ""
echo "EXPECT_DISULFIDES is set to 0. If this protein has disulfides, edit the conf"
echo "now -- prep_system.sh will stop if what pdb2gmx finds disagrees."
echo ""
echo "Next:"
if [ "${HAS_LIGAND}" = "1" ]; then
  echo "  LIGAND=${LIGAND} python3 02_build_glycan.py ${NAME}   # pose -> CHARMM topology"
fi
echo "  ./prep_system.sh ${NAME}                     # build the solvated box"
echo "  ./submit.sh ${NAME}                          # run ${N_REPS:-3} replicates on GPU"
